image: python3.5

services:
    - postgres9.5
    
variables:
  POSTGRES_DB: ci
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "postgres"

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - python -V
  
install:
    - "pip install -r requirements.txt"
    - "pip install -r testing_requirements.txt"
    - "pip install coveralls"

test:
    script:
    - export DATABASE_URL=postgres://postgres:@postgres:5432/ci
    - "flake8 ."
    - "./streisand/manage.py makemigrations"
    - "./streisand/manage.py migrate"
    - "coverage run ./streisand/manage.py test streisand"

after_success:
    - coveralls
    